---
- name: "Add the 1password ubuntu repo"
  ansible.builtin.deb822_repository:
    name: "1password"
    types: "deb"
    architectures: "amd64"
    uris: "https://downloads.1password.com/linux/debian/amd64"
    suites: "stable"
    components: "main"
    signed_by: "https://downloads.1password.com/linux/keys/1password.asc"
    state: "present"
    enabled: "yes"
  notify: 'linux_apt-get-update'

- name: "Use the 1password repo only for specific packages"
  become: true
  copy:
    content: |
      Package: *
      Pin: origin downloads.1password.com
      Pin-Priority: 100

      Package: 1password*
      Pin: origin downloads.1password.com
      Pin-Priority: 1000
    dest: "/etc/apt/preferences.d/1password"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: 'linux_apt-get-update'

- meta: flush_handlers

- name: "Install 1password desktop + cli"
  become: true
  apt:
    name:
      - "1password"
      - "1password-cli"
    state: "present"
