---
- name: "Add the Docker ubuntu repo"
  ansible.builtin.deb822_repository:
    name: "docker"
    types: "deb"
    architectures: "amd64"
    uris: "https://download.docker.com/linux/ubuntu"
    suites: "{{ansible_distribution_release|lower}}"
    components: "stable"
    signed_by: "https://download.docker.com/linux/ubuntu/gpg"
    state: "present"
    enabled: "yes"
  notify: 'linux_apt-get-update'

- name: "Use the Docker repo only for docker related packages"
  become: true
  copy:
    content: |
      Package: *
      Pin: origin download.docker.com
      Pin-Priority: 100

      Package: docker-ce* containerd*
      Pin: origin download.docker.com
      Pin-Priority: 1000
    dest: "/etc/apt/preferences.d/docker"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: 'linux_apt-get-update'

- meta: flush_handlers

- name: "Install docker"
  become: true
  apt:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
    state: "present"

- name: "Tools needed for multiarch builds"
  become: true
  apt:
    name:
      - "qemu-user-static"
      - "binfmt-support"
    state: "present"

- name: "Create the /etc/docker directory"
  become: true
  file:
    path: "/etc/docker"
    state: "directory"
    mode: "0700"

- name: "Add any additional docker startup options via the daemon.json config file"
  become: true
  copy:
    content: |
      {
        "userns-remap": "marvin",
        "experimental": true
      }
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: "0600"
  notify: "linux_restart-docker"

- name: "Start the docker service"
  become: true
  service:
    name: "docker"
    state: "started"
    enabled: "yes"

- name: "Allow the 'marvin' user to comfortably mount volumes while using docker user namespacing"
  become: true
  copy:
    content: "marvin:1000:2\nmarvin:100000:65535"
    dest: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "/etc/subuid"
    - "/etc/subgid"
  notify: "linux_restart-docker"

- meta: flush_handlers
