---
- name: "Add the keybase apt signing key"
  become: true
  apt_key:
    url: "https://keybase.io/docs/server_security/code_signing_key.asc"
    state: "present"

- name: "Add the keybase ubuntu repo"
  become: true
  copy:
    dest: '/etc/apt/sources.list.d/keybase.list'
    content: |
      deb http://prerelease.keybase.io/deb stable main

    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'linux_apt-get-update'

- meta: flush_handlers

- name: "Install Keybase"
  become: true
  apt:
    name: "keybase"
    state: "present"
