---
- name: "Install language-pack-en-base"
  become: true
  apt:
    pkg: "language-pack-en-base"
    state: "present"

- name: "Set the default locale"
  become: true
  copy:
    content: |
      LANG=en_US.UTF-8
      LC_ALL=en_US.UTF-8
      
    dest: "/etc/default/locale"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "linux_purge-extra-locales"
    - "linux_reconfigure-locales"

- meta: flush_handlers
