---
- name: "Add marvinpinto/kitchensink as a tap"
  become: true
  become_user: "marvin"
  community.general.homebrew_tap:
    name: "marvinpinto/kitchensink"
    url: "https://github.com/marvinpinto/kitchensink.git"

- name: "Install all the homebrew managed apps"
  become: true
  become_user: "marvin"
  community.general.homebrew:
    name:
      - "marvinpinto/kitchensink/op"
      - "aws-vault"
      - "cheat"
      - "marvinpinto/kitchensink/digikam"
      - "fzf"
      - "git"
      - "ansible"
      - "git-lfs"
      - "marvinpinto/kitchensink/inkscape"
      - "marvinpinto/kitchensink/kdenlive"
      - "mkcert"
      - "neovim"
      - "marvinpinto/kitchensink/openaudible"
      - "marvinpinto/kitchensink/peek"
      - "marvinpinto/kitchensink/plexamp"
      - "rclone"
      - "jq"
      - "git-delta"
      - "tree"
      - "the_silver_searcher"
      - "python"
      - "iftop"
      - "htop"
      - "xclip"
      - "tmux"
      - "smug"
      - "age"
      - "restic"
      - "tio"
    state: "present"
    path: "/home/linuxbrew/.linuxbrew/bin"

- name: "Install base Ubuntu programs"
  become: true
  apt:
    name:
      - "lightdm"
      - "vim-gtk"
      - "tmux"
      - "fonts-inconsolata"
      - "scrot"
      - "imagemagick"
      - "xautolock"
      - "whois"
      - "touchegg"
      - "linux-generic"
      - "xournal"
      - "audacity"
      - "default-jre"
      - "cpulimit"
      - "language-pack-en-base"
      - "tzdata"
      - "ca-certificates"
      - "net-tools"
      - "simple-scan"
      - "traceroute"
    state: "present"

- name: "Remove a few things I do not care for"
  become: true
  apt:
    name:
      - "avahi-daemon"
      - "apport"
      - "libreoffice-base-core"
      - "rhythmbox"
      - "thunderbird"
      - "evolution-data-server"
      - "empathy"
      - "duplicity"
      - "friends"
      - "remmina"
      - "shotwell"
      - "shotwell-common"
      - "telepathy-gabble"
      - "telepathy-haze"
      - "telepathy-idle"
      - "telepathy-indicator"
      - "telepathy-logger"
      - "telepathy-mission-control-5"
      - "totem"
      - "libreoffice-avmedia-backend-gstreamer"
      - "libreoffice-common"
      - "libreoffice-core"
      - "libreoffice-draw"
      - "libreoffice-gnome"
      - "libreoffice-gtk"
      - "libreoffice-impress"
      - "libreoffice-math"
      - "libreoffice-ogltrans"
      - "libreoffice-pdfimport"
      - "libreoffice-presentation-minimizer"
      - "libreoffice-style-human"
      - "account-plugin-facebook"
      - "account-plugin-flickr"
      - "account-plugin-google"
      - "libaccount-plugin-generic-oauth"
      - "libaccount-plugin-google"
      - "libpam-gnome-keyring"
      - "flashplugin-installer"
      - "evince"
      - "evince-common"
      - "brltty"
      - "cups-browsed"
      - "speech-dispatcher"
      - "modem-manager"
      - "command-not-found"
    state: "absent"
    purge: "yes"

- name: "Delete the ubuntu startup drumbeat sound"
  become: true
  file:
    path: "/usr/share/sounds/ubuntu/stereo/system-ready.ogg"
    state: "absent"
