---
- name: "Install rofi"
  become: true
  apt:
    name: "rofi"
    state: "present"

- name: "Install some rofi-related goodies"
  become: true
  apt:
    name:
      - "gawk"
      - "xdotool"
      - "libxml2-utils"
    state: "present"
