---
- name: "Add the tailscale ubuntu repo"
  ansible.builtin.deb822_repository:
    name: "tailscale"
    types: "deb"
    architectures: "amd64"
    uris: "https://pkgs.tailscale.com/stable/ubuntu"
    suites: "{{ ansible_distribution_release }}"
    components: "main"
    signed_by: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.gpg"
    state: "present"
    enabled: "yes"
  notify: 'linux_apt-get-update'

- name: "Use the tailscale repo only for specific packages"
  become: true
  copy:
    content: |
      Package: *
      Pin: origin pkgs.tailscale.com
      Pin-Priority: 100

      Package: tailscale
      Pin: origin pkgs.tailscale.com
      Pin-Priority: 1000
    dest: "/etc/apt/preferences.d/tailscale"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: 'linux_apt-get-update'

- meta: flush_handlers

- name: "Install tailscale"
  become: true
  apt:
    name: "tailscale"
    state: "present"

- name: "Enable the tailscale service"
  become: true
  service:
    name: "tailscaled"
    state: "stopped"
    enabled: "no"
