---
- name: "Add the virtualbox apt signing keys"
  become: true
  apt_key:
    url: "{{ item }}"
    state: "present"
  with_items:
    - "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    - "https://www.virtualbox.org/download/oracle_vbox.asc"

- name: "Add the Virtualbox ubuntu repo"
  become: true
  apt_repository:
    repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: "present"
    update_cache: "yes"
    filename: "virtualbox"

- name: "Install Virtualbox"
  vars:
    virtualbox_major_version: "6"
    virtualbox_minor_version: "1"
    virtualbox_patch_version: "20"
  become: true
  apt:
    name:
      - "virtualbox-{{virtualbox_major_version}}.{{virtualbox_minor_version}}"
      - "dkms"
    state: "present"

- name: "Create the /usr/local/etc/virtualbox directory"
  become: true
  file:
    path: "/usr/local/etc/virtualbox"
    state: "directory"
    mode: "0755"

- name: "Check to see if the extension pack file exists"
  vars:
    virtualbox_major_version: "6"
    virtualbox_minor_version: "1"
    virtualbox_patch_version: "20"
  become: true
  stat:
    path: "/usr/local/etc/virtualbox/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}.vbox-extpack"
  register: "extension_pack_binary"

- name: "Download the extension pack"
  vars:
    virtualbox_major_version: "6"
    virtualbox_minor_version: "1"
    virtualbox_patch_version: "20"
  become: true
  get_url:
    url: "http://download.virtualbox.org/virtualbox/{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}.vbox-extpack"
    dest: "/usr/local/etc/virtualbox/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}.vbox-extpack"
    mode: "0755"
  when: "extension_pack_binary.stat.exists == False"

- name: "Install the extension pack"
  vars:
    virtualbox_major_version: "6"
    virtualbox_minor_version: "1"
    virtualbox_patch_version: "20"
  become: true
  shell: "echo y | /usr/bin/VBoxManage extpack install --replace /usr/local/etc/virtualbox/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}.vbox-extpack"
  when: "extension_pack_binary.stat.exists == False"

- name: "Add marvin to the vboxusers group"
  become: true
  user:
    name: "marvin"
    groups: "vboxusers"
    append: "yes"
