---
- name: "Add the Virtualbox ubuntu repo"
  ansible.builtin.deb822_repository:
    name: "virtualbox"
    types: "deb"
    architectures: "amd64"
    uris: "http://download.virtualbox.org/virtualbox/debian"
    suites: "{{ ansible_distribution_release }}"
    components: "contrib"
    signed_by: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    state: "present"
    enabled: "yes"
  notify: 'linux_apt-get-update'

- name: "Use the Virtualbox repo only for specific packages"
  become: true
  copy:
    content: |
      Package: *
      Pin: origin download.virtualbox.org
      Pin-Priority: 100

      Package: virtualbox-*
      Pin: origin download.virtualbox.org
      Pin-Priority: 1000
    dest: "/etc/apt/preferences.d/virtualbox"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: 'linux_apt-get-update'

- meta: flush_handlers

# NOTE: Virtualbox major/minor/patch version info is at https://www.virtualbox.org/wiki/Downloads

- name: "Install Virtualbox"
  vars:
    virtualbox_major_version: "7"
    virtualbox_minor_version: "0"
    virtualbox_patch_version: "14"
  become: true
  apt:
    name:
      - "virtualbox-{{virtualbox_major_version}}.{{virtualbox_minor_version}}"
      - "dkms"
    state: "present"

- name: "Create the /usr/local/etc/virtualbox directory"
  become: true
  file:
    path: "/usr/local/etc/virtualbox"
    state: "directory"
    mode: "0755"

- name: "Check to see if the extension pack file exists"
  vars:
    virtualbox_major_version: "7"
    virtualbox_minor_version: "0"
    virtualbox_patch_version: "14"
  become: true
  stat:
    path: "/usr/local/etc/virtualbox/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}.vbox-extpack"
  register: "extension_pack_binary"

- name: "Download the extension pack"
  vars:
    virtualbox_major_version: "7"
    virtualbox_minor_version: "0"
    virtualbox_patch_version: "14"
  become: true
  get_url:
    url: "http://download.virtualbox.org/virtualbox/{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}.vbox-extpack"
    dest: "/usr/local/etc/virtualbox/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}.vbox-extpack"
    mode: "0755"
  when: "extension_pack_binary.stat.exists == False"

- name: "Install the extension pack"
  vars:
    virtualbox_major_version: "7"
    virtualbox_minor_version: "0"
    virtualbox_patch_version: "14"
  become: true
  shell: "echo y | /usr/bin/VBoxManage extpack install --replace /usr/local/etc/virtualbox/Oracle_VM_VirtualBox_Extension_Pack-{{virtualbox_major_version}}.{{virtualbox_minor_version}}.{{virtualbox_patch_version}}.vbox-extpack"
  when: "extension_pack_binary.stat.exists == False"

- name: "Add marvin to the vboxusers group"
  become: true
  user:
    name: "marvin"
    groups: "vboxusers"
    append: "yes"
