---
- name: "Install a few requirements needed by the various yubikey tools"
  become: true
  apt:
    name:
      - "gnupg2"
      - "pinentry-curses"
      - "pcscd"
      - "scdaemon"
      - "pcsc-tools"
    state: "latest"
  notify: "linux_restart-pcscd"

- name: "Install the Yubikey personalization tools"
  become: true
  apt:
    name:
      - "yubikey-personalization"
      - "yubikey-personalization-gui"
      - "yubioath-desktop"
    state: "present"

- name: "Install the yubikey-manager package"
  become: true
  apt:
    name:
      - "yubikey-manager"
      - "python3-yubikey-manager"
    state: "present"

- meta: flush_handlers
