---
name: kitchensink
root: ~/projects/kitchensink

startup_window: code

windows:
  - notes: note ls
  - code: vim
  - cli:
      layout: main-vertical
      panes:
        - git:
          - ls -al
          - git status
        - run:
          - ls -al
        - misc:
          - ls -al
