---
- name: "Get user profile path"
  changed_when: false
  ansible.windows.win_command: "powershell.exe -"
  args:
    stdin: "echo $HOME"
  register: "user_home_path"

- name: "List all the desktop shortcuts"
  changed_when: false
  ansible.windows.win_find:
    paths:
      - '{{ user_home_path.stdout | trim }}\Desktop'
      - 'C:\Users\Public\Desktop'
    patterns: "*.lnk"
  register: "shortcuts"

- name: "Only keep a few desktop shortcuts"
  vars:
    shortcuts_to_keep:
      - "Firefox.lnk"
      - "Alacritty.lnk"
      - "Notepad++.lnk"
      - "Spotify.lnk"
      - "Division 2.lnk"
      - "Aim Lab.lnk"
  win_file:
    path: "{{ item.path }}"
    state: "absent"
  with_items: "{{ shortcuts.files }}"
  when: "item.filename not in shortcuts_to_keep"
