---
name: "Latest Release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

  schedule:
    # run this job at 04:00hrs every day
    - cron:  "0 4 * * *"

permissions:
  contents: "read"
  packages: "write"

jobs:
  gh_latest:
    runs-on: "ubuntu-latest"
    env:
      UBUNTU_LTS_VERSION: "20.04"
    steps:
      - uses: "actions/checkout@v2.4.0"
        with:
          lfs: true
          fetch-depth: 0

      - name: "Retrieve the short SHA"
        id: "sha"
        run: echo "::set-output name=value::$(echo ${GITHUB_SHA::8})"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v1.2.0"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2.4.0"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v1.12.0"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Publish to GitHub Packages"
        uses: "docker/build-push-action@v2.7.0"
        with:
          context: .
          file: "./Dockerfile"
          build-args: |
            UBUNTU_VERSION=${{ env.UBUNTU_LTS_VERSION }}
          platforms: "linux/amd64"
          push: true
          tags: |
            ghcr.io/marvinpinto/kitchensink:${{ env.UBUNTU_LTS_VERSION }}-latest
            ghcr.io/marvinpinto/kitchensink:${{ env.UBUNTU_LTS_VERSION }}-${{ steps.sha.outputs.value }}

      - uses: "marvinpinto/action-keybase-notifications@latest"
        if: always()
        with:
          job_status: ${{ job.status }}
          on_success: "never"
          on_failure: "always"
          opensentinel_token: ${{ secrets.OSL_TOKEN }}
